spring:
  application:
    name: cities-service
  cloud:
    circuitbreaker:
      resilience4j:
        enable-auto-configuration: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hotelAPI:
    url: hotels-service
